import { render } from "solid-js/web";
import { createSignal } from "solid-js";
import "./style.css";
// Type-safe bindings generated by jdesk-codegen (./gradlew bindings); the jdesk-client
// runtime handles the nonce/hello handshake, correlation, timeouts, and cancellation.
import { commands } from "./generated/commands";

function App() {
  const [status, setStatus] = createSignal("Ready");
  const [name, setName] = createSignal("JDesk");

  async function greet(event) {
    event.preventDefault();
    try {
      const response = await commands.greeting.greet({ name: name() });
      setStatus(response.message);
    } catch (error) {
      setStatus(`${error.code ?? "ERROR"}: ${error.message}`);
    }
  }

  return (
    <main>
      <h1>@PROJECT_NAME@</h1>
      <form onSubmit={greet}>
        <input value={name()} onInput={(event) => setName(event.currentTarget.value)} />
        <button>Greet</button>
      </form>
      <p>{status()}</p>
    </main>
  );
}

render(() => <App />, document.getElementById("root"));
