package dev.jdesk.codegen;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.Map;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Spec section 11: identical inputs must produce byte-identical output — no timestamps,
 * no absolute paths, no unordered iteration. Golden files live in
 * src/test/resources/golden/. To update a golden after an intentional emitter change:
 * run the test, copy the actual file it writes under the temp dir (the assertion message
 * shows the diff), or regenerate by compiling the fixture in Fixtures.java and pasting
 * the emitted content verbatim. Never hand-edit generated content semantics.
 */
class DeterminismGoldenTest {

    @Test
    void identicalInputProducesByteIdenticalOutputAcrossRuns(@TempDir Path first,
            @TempDir Path second) throws IOException {
        Map<String, String> sources = Map.of(
                Fixtures.GREETING_SERVICE_NAME, Fixtures.GREETING_SERVICE,
                Fixtures.CATALOG_SERVICE_NAME, Fixtures.CATALOG_SERVICE);

        TestCompiler.Result a = TestCompiler.compile(first, sources);
        TestCompiler.Result b = TestCompiler.compile(second, sources);
        assertThat(a.success()).as(a.errorText()).isTrue();
        assertThat(b.success()).as(b.errorText()).isTrue();

        Map<String, byte[]> filesA = a.generatedFiles();
        Map<String, byte[]> filesB = b.generatedFiles();
        assertThat(filesA.keySet())
                .contains("com/example/app/GreetingServiceCommands.java",
                        "com/example/app/CatalogServiceCommands.java",
                        "com/example/app/JDeskCommands.java",
                        "jdesk-ts/types.ts",
                        "jdesk-ts/commands.ts")
                .isEqualTo(filesB.keySet());
        for (Map.Entry<String, byte[]> entry : filesA.entrySet()) {
            assertThat(filesB.get(entry.getKey()))
                    .as("byte-identical content for %s", entry.getKey())
                    .isEqualTo(entry.getValue());
        }
    }

    @Test
    void generatedJavaMatchesGoldenFixture(@TempDir Path dir) throws IOException {
        TestCompiler.Result result = TestCompiler.compile(dir,
                Map.of(Fixtures.GREETING_SERVICE_NAME, Fixtures.GREETING_SERVICE));
        assertThat(result.success()).as(result.errorText()).isTrue();
        assertThat(result.generatedSource("com.example.app.GreetingServiceCommands"))
                .isEqualTo(golden("GreetingServiceCommands.java.golden"));
    }

    @Test
    void generatedTypeScriptMatchesGoldenFixture(@TempDir Path dir) throws IOException {
        TestCompiler.Result result = TestCompiler.compile(dir,
                Map.of(Fixtures.GREETING_SERVICE_NAME, Fixtures.GREETING_SERVICE));
        assertThat(result.success()).as(result.errorText()).isTrue();
        assertThat(result.tsFile("types.ts")).isEqualTo(golden("greeting-types.ts.golden"));
        assertThat(result.tsFile("commands.ts")).isEqualTo(golden("greeting-commands.ts.golden"));
    }

    @Test
    void generatedFilesCarryFixedHeaderAndNoAbsolutePaths(@TempDir Path dir) throws IOException {
        TestCompiler.Result result = TestCompiler.compile(dir,
                Map.of(Fixtures.GREETING_SERVICE_NAME, Fixtures.GREETING_SERVICE));
        assertThat(result.success()).as(result.errorText()).isTrue();
        for (Map.Entry<String, byte[]> entry : result.generatedFiles().entrySet()) {
            String content = new String(entry.getValue(), StandardCharsets.UTF_8);
            assertThat(content)
                    .as("header in %s", entry.getKey())
                    .startsWith("// Generated by jdesk-codegen. Do not edit.");
            assertThat(content)
                    .as("no absolute paths in %s", entry.getKey())
                    .doesNotContain(dir.toString());
        }
    }

    static String golden(String name) throws IOException {
        try (InputStream in = DeterminismGoldenTest.class
                .getResourceAsStream("/golden/" + name)) {
            assertThat(in).as("golden resource /golden/" + name).isNotNull();
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        }
    }
}
