package dev.jdesk.codegen;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class HappyPathTest {

    @Test
    void serviceWithTwoCommandsCompilesAndGeneratesRegistry(@TempDir Path dir) throws IOException {
        TestCompiler.Result result = TestCompiler.compile(dir,
                Map.of(Fixtures.GREETING_SERVICE_NAME, Fixtures.GREETING_SERVICE));

        assertThat(result.success()).as(result.errorText()).isTrue();
        String generated = result.generatedSource("com.example.app.GreetingServiceCommands");
        assertThat(generated)
                .startsWith("// Generated by jdesk-codegen. Do not edit.")
                .contains("public static dev.jdesk.api.CommandRegistry create("
                        + "com.example.app.GreetingService instance)")
                .contains("\"greeting.greet\"")
                .contains("java.util.Optional.of(\"greeting.read\")")
                .contains("com.example.app.GreetingService.GreetRequest.class")
                .contains("\"greeting.ping\"")
                .contains("java.lang.Void.class")
                .contains("(request, context) -> instance.ping(context)");
        // greeting.greet sorts before greeting.ping.
        assertThat(generated.indexOf("greeting.greet"))
                .isLessThan(generated.indexOf("greeting.ping"));
    }

    @Test
    void generatedRegistryCompilesInSecondJavacRound(@TempDir Path dir) throws IOException {
        TestCompiler.Result first = TestCompiler.compile(dir,
                Map.of(Fixtures.GREETING_SERVICE_NAME, Fixtures.GREETING_SERVICE));
        assertThat(first.success()).as(first.errorText()).isTrue();

        TestCompiler.Result second = TestCompiler.compileGenerated(dir, first);
        assertThat(second.success()).as(second.errorText()).isTrue();
        assertThat(second.classesDir()
                .resolve("com/example/app/GreetingServiceCommands.class")).exists();
    }

    @Test
    void noArgsCommandIsSupported(@TempDir Path dir) throws IOException {
        TestCompiler.Result result = TestCompiler.compile(dir, Map.of("com.example.app.TestService",
                Fixtures.service("""
                        @DesktopCommand("app.version")
                        @PublicDesktopCommand
                        public CompletionStage<String> version() {
                            return null;
                        }
                        """)));
        assertThat(result.success()).as(result.errorText()).isTrue();
        assertThat(result.generatedSource("com.example.app.TestServiceCommands"))
                .contains("(request, context) -> instance.version()");
    }

    @Test
    void aggregatorIsGeneratedWhenPackageHasTwoServices(@TempDir Path dir) throws IOException {
        String second = """
                package com.example.app;

                import dev.jdesk.api.DesktopCommand;
                import dev.jdesk.api.InvocationContext;
                import dev.jdesk.api.RequiresCapability;
                import java.util.concurrent.CompletionStage;

                public class FileService {

                    @DesktopCommand("file.stat")
                    @RequiresCapability("fs.read")
                    public CompletionStage<String> stat(String path, InvocationContext context) {
                        return null;
                    }
                }
                """;
        TestCompiler.Result result = TestCompiler.compile(dir, Map.of(
                Fixtures.GREETING_SERVICE_NAME, Fixtures.GREETING_SERVICE,
                "com.example.app.FileService", second));
        assertThat(result.success()).as(result.errorText()).isTrue();
        assertThat(result.generatedSource("com.example.app.JDeskCommands"))
                .contains("public static dev.jdesk.api.CommandRegistry combine("
                        + "dev.jdesk.api.CommandRegistry... registries)");

        TestCompiler.Result compiled = TestCompiler.compileGenerated(dir, result);
        assertThat(compiled.success()).as(compiled.errorText()).isTrue();
    }

    @Test
    void aggregatorIsNotGeneratedForSingleService(@TempDir Path dir) throws IOException {
        TestCompiler.Result result = TestCompiler.compile(dir,
                Map.of(Fixtures.GREETING_SERVICE_NAME, Fixtures.GREETING_SERVICE));
        assertThat(result.success()).as(result.errorText()).isTrue();
        assertThat(result.generatedSourceExists("com.example.app.JDeskCommands")).isFalse();
    }

    @Test
    void processorIsRegisteredForServiceLoaderDiscovery() throws IOException {
        // The packaged registration file must name the processor class.
        Path services = Path.of("src/main/resources/META-INF/services/"
                + "javax.annotation.processing.Processor");
        assertThat(services).exists();
        assertThat(Files.readString(services, StandardCharsets.UTF_8).strip())
                .isEqualTo("dev.jdesk.codegen.DesktopCommandProcessor");
    }

    @Test
    void processorIsDiscoveredViaProcessorPath(@TempDir Path dir) throws IOException {
        // Simulate ServiceLoader discovery the way javac does it on -processorpath:
        // classes plus a META-INF/services entry, no explicit -processor option.
        Path processorPath = Files.createDirectories(dir.resolve("processor-path"));
        Path servicesFile = processorPath.resolve(
                "META-INF/services/javax.annotation.processing.Processor");
        Files.createDirectories(servicesFile.getParent());
        Files.writeString(servicesFile, "dev.jdesk.codegen.DesktopCommandProcessor\n",
                StandardCharsets.UTF_8);

        Path sourceDir = Files.createDirectories(dir.resolve("src"));
        Path source = sourceDir.resolve("com/example/app/GreetingService.java");
        Files.createDirectories(source.getParent());
        Files.writeString(source, Fixtures.GREETING_SERVICE, StandardCharsets.UTF_8);
        Path classes = Files.createDirectories(dir.resolve("classes"));
        Path generated = Files.createDirectories(dir.resolve("generated"));

        String pathSeparator = java.io.File.pathSeparator;
        javax.tools.JavaCompiler compiler = javax.tools.ToolProvider.getSystemJavaCompiler();
        int exitCode = compiler.run(null, null, null,
                "-classpath", TestCompiler.apiClasspath(),
                "-processorpath", TestCompiler.processorClasspath() + pathSeparator
                        + TestCompiler.apiClasspath() + pathSeparator + processorPath,
                "-d", classes.toString(),
                "-s", generated.toString(),
                "-encoding", "UTF-8",
                source.toString());
        assertThat(exitCode).isZero();
        assertThat(generated.resolve("com/example/app/GreetingServiceCommands.java")).exists();
        assertThat(classes.resolve("jdesk-ts/types.ts")).exists();
    }

    @Test
    void multipleTopLevelSegmentsProduceNestedNamespaces(@TempDir Path dir) throws IOException {
        TestCompiler.Result result = TestCompiler.compile(dir, Map.of("com.example.app.TestService",
                Fixtures.service("""
                        @DesktopCommand("app.settings.get")
                        @PublicDesktopCommand
                        public CompletionStage<String> getSetting(String key, InvocationContext context) {
                            return null;
                        }

                        @DesktopCommand("app.quit")
                        @PublicDesktopCommand
                        public CompletionStage<Void> quit(InvocationContext context) {
                            return null;
                        }
                        """)));
        assertThat(result.success()).as(result.errorText()).isTrue();
        assertThat(result.tsFile("commands.ts"))
                .contains("app: {")
                .contains("settings: {")
                .contains("quit(): Promise<void> {")
                .contains("return invoke(\"app.settings.get\", request) as Promise<string>;");
    }

    @Test
    void generatedFilesArePlacedInEachServicePackage(@TempDir Path dir) throws IOException {
        String other = """
                package com.example.files;

                import dev.jdesk.api.DesktopCommand;
                import dev.jdesk.api.InvocationContext;
                import dev.jdesk.api.RequiresCapability;
                import java.util.concurrent.CompletionStage;

                public class FileService {

                    @DesktopCommand("file.read")
                    @RequiresCapability("fs.read")
                    public CompletionStage<String> read(String token, InvocationContext context) {
                        return null;
                    }
                }
                """;
        TestCompiler.Result result = TestCompiler.compile(dir, Map.of(
                Fixtures.GREETING_SERVICE_NAME, Fixtures.GREETING_SERVICE,
                "com.example.files.FileService", other));
        assertThat(result.success()).as(result.errorText()).isTrue();
        assertThat(result.generatedSourceExists("com.example.app.GreetingServiceCommands")).isTrue();
        assertThat(result.generatedSourceExists("com.example.files.FileServiceCommands")).isTrue();
        // Different packages: no aggregator anywhere.
        assertThat(result.generatedSourceExists("com.example.app.JDeskCommands")).isFalse();
        assertThat(result.generatedSourceExists("com.example.files.JDeskCommands")).isFalse();
        List<String> files = result.generatedFiles().keySet().stream().toList();
        assertThat(files).contains("jdesk-ts/types.ts", "jdesk-ts/commands.ts");
    }
}
