import "./style.css";
// Type-safe bindings generated by jdesk-codegen (./gradlew bindings); the jdesk-client
// runtime handles the nonce/hello handshake, correlation, timeouts, and cancellation.
import { commands } from "./generated/commands";

const result = document.querySelector("#result");
result.textContent = "Ready";

document.querySelector("#greet").addEventListener("submit", async (event) => {
  event.preventDefault();
  try {
    const response = await commands.greeting.greet({
      name: document.querySelector("#name").value,
    });
    result.textContent = response.message;
  } catch (error) {
    result.textContent = `${error.code ?? "ERROR"}: ${error.message}`;
  }
});
