import { createApp, ref } from "vue";
import "./style.css";
// Type-safe bindings generated by jdesk-codegen (./gradlew bindings); the jdesk-client
// runtime handles the nonce/hello handshake, correlation, timeouts, and cancellation.
import { commands } from "./generated/commands";

createApp({
  setup() {
    const name = ref("JDesk");
    const status = ref("Ready");
    const greet = async () => {
      try {
        const response = await commands.greeting.greet({ name: name.value });
        status.value = response.message;
      } catch (error) {
        status.value = `${error.code ?? "ERROR"}: ${error.message}`;
      }
    };
    return { name, status, greet };
  },
  template: `<main><h1>@PROJECT_NAME@</h1><form @submit.prevent="greet">
      <input v-model="name"><button>Greet</button></form><p>{{status}}</p></main>`,
}).mount("#app");
