import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";
// Type-safe bindings generated by jdesk-codegen (./gradlew bindings); the jdesk-client
// runtime handles the nonce/hello handshake, correlation, timeouts, and cancellation.
import { commands } from "./generated/commands";

const h = React.createElement;

function App() {
  const [status, setStatus] = useState("Ready");
  const [name, setName] = useState("JDesk");

  async function greet(event) {
    event.preventDefault();
    try {
      const response = await commands.greeting.greet({ name });
      setStatus(response.message);
    } catch (error) {
      setStatus(`${error.code ?? "ERROR"}: ${error.message}`);
    }
  }

  return h("main", null,
    h("h1", null, "@PROJECT_NAME@"),
    h("form", { onSubmit: greet },
      h("input", { value: name, onChange: (event) => setName(event.target.value) }),
      h("button", null, "Greet")),
    h("p", null, status));
}

createRoot(document.getElementById("root")).render(h(App));
