package dev.jdesk.codegen;

import java.util.List;

/**
 * Emits deterministic Java sources: one {@code <Service>Commands} registry class per
 * annotated service, and the constant {@code JDeskCommands} aggregator. Fully qualified
 * names are used throughout so no import resolution is needed; content depends only on
 * the validated command models.
 */
final class JavaEmitter {

    static final String HEADER = "// Generated by jdesk-codegen. Do not edit.\n";

    private JavaEmitter() {
    }

    /** Source of {@code <Service>Commands} for one service class; commands sorted by name. */
    static String serviceRegistry(String packageName, String generatedSimpleName,
            String serviceQualifiedName, List<CommandModel> commands) {
        StringBuilder b = new StringBuilder();
        b.append(HEADER);
        if (!packageName.isEmpty()) {
            b.append("package ").append(packageName).append(";\n");
        }
        b.append('\n');
        b.append("/** Command registry for {@code ").append(serviceQualifiedName).append("}. */\n");
        b.append("public final class ").append(generatedSimpleName).append(" {\n\n");
        b.append("    private ").append(generatedSimpleName).append("() {\n    }\n\n");
        b.append("    /** Creates a registry of every {@code @DesktopCommand} on the given service instance. */\n");
        b.append("    public static dev.jdesk.api.CommandRegistry create(")
                .append(serviceQualifiedName).append(" instance) {\n");
        b.append("        java.util.Objects.requireNonNull(instance, \"instance\");\n");
        b.append("        return dev.jdesk.api.CommandRegistry.of(");
        for (int i = 0; i < commands.size(); i++) {
            CommandModel command = commands.get(i);
            b.append("\n                new dev.jdesk.api.CommandDefinition(\n");
            b.append("                        \"").append(javaString(command.name())).append("\",\n");
            if (command.capability().isPresent()) {
                b.append("                        java.util.Optional.of(\"")
                        .append(javaString(command.capability().get())).append("\"),\n");
            } else {
                b.append("                        java.util.Optional.empty(),\n");
            }
            b.append("                        ").append(command.requestCanonicalName()).append(".class,\n");
            b.append("                        java.util.Optional.empty(),\n");
            b.append("                        ").append(handlerExpression(command)).append(')');
            b.append(i < commands.size() - 1 ? "," : ");\n    }\n}\n");
        }
        return b.toString();
    }

    private static String handlerExpression(CommandModel command) {
        return switch (command.shape()) {
            case REQUEST_AND_CONTEXT -> "(request, context) -> instance." + command.methodName()
                    + "((" + command.requestCanonicalName() + ") request, context)";
            case CONTEXT_ONLY -> "(request, context) -> instance." + command.methodName() + "(context)";
            case NO_ARGS -> "(request, context) -> instance." + command.methodName() + "()";
        };
    }

    /**
     * Source of the {@code JDeskCommands} aggregator, generated once per package that
     * declares more than one command service. Content is input-independent.
     */
    static String aggregator(String packageName) {
        StringBuilder b = new StringBuilder();
        b.append(HEADER);
        if (!packageName.isEmpty()) {
            b.append("package ").append(packageName).append(";\n");
        }
        b.append('\n');
        b.append("""
                /** Combines the command registries generated in this package. */
                public final class JDeskCommands {

                    private JDeskCommands() {
                    }

                    /** Combines several generated registries; duplicate command names fail fast. */
                    public static dev.jdesk.api.CommandRegistry combine(dev.jdesk.api.CommandRegistry... registries) {
                        java.util.List<dev.jdesk.api.CommandDefinition> definitions = new java.util.ArrayList<>();
                        for (dev.jdesk.api.CommandRegistry registry : registries) {
                            for (String name : registry.commandNames()) {
                                registry.find(name).ifPresent(definitions::add);
                            }
                        }
                        return dev.jdesk.api.CommandRegistry.of(
                                definitions.toArray(new dev.jdesk.api.CommandDefinition[0]));
                    }
                }
                """);
        return b.toString();
    }

    /** Escapes a string for use inside a Java string literal; non-ASCII becomes {@code \\uXXXX}. */
    static String javaString(String value) {
        StringBuilder b = new StringBuilder(value.length());
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            switch (c) {
                case '\\' -> b.append("\\\\");
                case '"' -> b.append("\\\"");
                case '\n' -> b.append("\\n");
                case '\r' -> b.append("\\r");
                case '\t' -> b.append("\\t");
                default -> {
                    if (c < 0x20 || c > 0x7e) {
                        b.append(String.format(java.util.Locale.ROOT, "\\u%04x", (int) c));
                    } else {
                        b.append(c);
                    }
                }
            }
        }
        return b.toString();
    }
}
