package dev.jdesk.codegen;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeSet;

/**
 * Emits deterministic TypeScript sources: {@code types.ts} (one interface per DTO record,
 * sorted by name) and {@code commands.ts} (a nested namespace object built from the
 * dot-separated command names, wired to the static runtime's {@code invoke}).
 */
final class TsEmitter {

    private static final String HEADER = "// Generated by jdesk-codegen. Do not edit.\n";

    private TsEmitter() {
    }

    /** Content of {@code types.ts}; records must already be sorted by TypeScript name. */
    static String typesTs(List<RecordModel> records) {
        StringBuilder b = new StringBuilder(HEADER);
        for (RecordModel record : records) {
            b.append("\nexport interface ").append(record.tsName());
            if (record.fields().isEmpty()) {
                b.append(" {}\n");
                continue;
            }
            b.append(" {\n");
            for (RecordModel.Field field : record.fields()) {
                b.append("  ").append(field.name()).append(": ").append(field.tsType()).append(";\n");
            }
            b.append("}\n");
        }
        return b.toString();
    }

    /** Content of {@code commands.ts}; commands must already be sorted by wire name. */
    static String commandsTs(List<CommandModel> commands) {
        StringBuilder b = new StringBuilder(HEADER);
        b.append("import { invoke } from \"@jdesk/client\";\n");
        TreeSet<String> imports = new TreeSet<>();
        for (CommandModel command : commands) {
            imports.addAll(command.tsReferencedRecords());
        }
        if (!imports.isEmpty()) {
            b.append("import type { ").append(String.join(", ", imports)).append(" } from \"./types\";\n");
        }
        Node root = new Node();
        for (CommandModel command : commands) {
            Node node = root;
            String[] segments = command.name().split("\\.");
            for (int i = 0; i < segments.length - 1; i++) {
                node = node.children.computeIfAbsent(segments[i], key -> new Node());
            }
            node.children.computeIfAbsent(segments[segments.length - 1], key -> new Node())
                    .command = command;
        }
        b.append("\nexport const commands = {\n");
        renderNode(b, root, 1);
        b.append("};\n");
        return b.toString();
    }

    private static void renderNode(StringBuilder b, Node node, int depth) {
        String indent = "  ".repeat(depth);
        for (Map.Entry<String, Node> entry : node.children.entrySet()) {
            Node child = entry.getValue();
            if (child.command != null) {
                CommandModel command = child.command;
                String parameter = command.tsRequestType() == null
                        ? "" : "request: " + command.tsRequestType();
                String argument = command.tsRequestType() == null ? "null" : "request";
                String promise = "Promise<" + command.tsResponseType() + ">";
                b.append(indent).append(entry.getKey()).append('(').append(parameter)
                        .append("): ").append(promise).append(" {\n");
                b.append(indent).append("  return invoke(\"").append(command.name())
                        .append("\", ").append(argument).append(") as ").append(promise).append(";\n");
                b.append(indent).append("},\n");
            } else {
                b.append(indent).append(entry.getKey()).append(": {\n");
                renderNode(b, child, depth + 1);
                b.append(indent).append("},\n");
            }
        }
    }

    /** Namespace tree node; a leaf carries the command, an inner node carries children. */
    private static final class Node {
        final Map<String, Node> children = new LinkedHashMap<>();
        CommandModel command;
    }
}
