<script>
  // Type-safe bindings generated by jdesk-codegen (./gradlew bindings); the
  // jdesk-client runtime handles the nonce/hello handshake and correlation.
  import { commands } from "./generated/commands";

  let name = $state("JDesk");
  let status = $state("Ready");

  async function greet(event) {
    event.preventDefault();
    try {
      const response = await commands.greeting.greet({ name });
      status = response.message;
    } catch (error) {
      status = `${error.code ?? "ERROR"}: ${error.message}`;
    }
  }
</script>
<main>
  <h1>@PROJECT_NAME@</h1>
  <form onsubmit={greet}><input bind:value={name}><button>Greet</button></form>
  <p>{status}</p>
</main>
